network_insta:
    resource: "@NetworkInstaBundle/Resources/config/routing.yml"
    prefix:   /

network_web:
    resource: "@NetworkWebBundle/Resources/config/routing.yml"
    prefix:   /

network_store:
    resource: "@NetworkStoreBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    path:  /
    defaults: { _controller: NetworkWebBundle:Default:index }
    requirements:
        _method: GET

oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /connect

oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

instagram_login:
    pattern: /login/check-instagram
    defaults: { _controller: NetworkInstaBundle:CheckLogin:getCode }