services:
#    network_insta.example:
#        class: Network\InstaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    network.oauthprovider:
      class: Network\InstaBundle\Controller\OAuthProvider